# Generated by Django 4.2 on 2026-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField(blank=True, null=True)),
                ('fare', models.FloatField(blank=True, null=True)),
                ('embarked', models.CharField(max_length=1)),
                ('family_size', models.IntegerField(blank=True, null=True)),
                ('is_alone', models.BooleanField(default=False)),
                ('survived', models.BooleanField()),
                ('survival_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
